import { ServiceError } from '../../domain/errors';
import type { Encryption } from '../../ports/credentials';
import type { EventConsumer, EventConsumerStore } from '../../ports/event-consumers';
import type { SqlDatabase } from './sql';
export class SqliteEventConsumerStore implements EventConsumerStore {
    constructor(private readonly sql: SqlDatabase, private readonly encryption: Encryption, private readonly limits = {maxActivePerOwner:100,maxRecords:1000,maxBytes:32*1024*1024}) {
        sql.exec('CREATE TABLE IF NOT EXISTS event_revoked_owners (owner TEXT PRIMARY KEY)');
        sql.exec('CREATE TABLE IF NOT EXISTS event_consumers (id TEXT PRIMARY KEY, owner TEXT NOT NULL, revision INTEGER NOT NULL, expires INTEGER NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL)');
        sql.exec('CREATE INDEX IF NOT EXISTS event_consumer_expiry ON event_consumers(status, expires)');
        sql.exec('CREATE TABLE IF NOT EXISTS event_consumer_groups (id TEXT PRIMARY KEY, leader TEXT NOT NULL, state TEXT NOT NULL)');
        sql.exec('CREATE TABLE IF NOT EXISTS event_consumer_members (group_id TEXT NOT NULL, consumer_id TEXT NOT NULL, PRIMARY KEY(group_id, consumer_id))');
    }
    async revokeOwner(owner: string): Promise<void> { this.sql.exec('INSERT OR IGNORE INTO event_revoked_owners(owner) VALUES(?)', owner); }
    async ownerRevoked(owner: string): Promise<boolean> { return [...this.sql.exec('SELECT owner FROM event_revoked_owners WHERE owner=?', owner)].length > 0; }
    private async encode(record: EventConsumer): Promise<string> { const text = JSON.stringify(record); if (new TextEncoder().encode(text).length > 512 * 1024) throw new ServiceError('EVENT_STATE_LIMIT', 'Event consumer state exceeds 512 KiB.', 413); return this.encryption.encrypt(`event-consumer:${record.owner}:${record.id}`, text); }
    private async decode(row: Record<string, unknown>): Promise<EventConsumer> { return JSON.parse(await this.encryption.decrypt(`event-consumer:${row.owner}:${row.id}`, String(row.payload))) as EventConsumer; }
    async create(record: EventConsumer): Promise<void> { const payload = await this.encode(record); const rows=[...this.sql.exec("INSERT INTO event_consumers(id,owner,revision,expires,status,payload) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM event_consumers WHERE owner=? AND status!='stopped')<? AND (SELECT COUNT(*) FROM event_consumers)<? AND (SELECT COALESCE(SUM(length(payload)),0) FROM event_consumers)+?<=? RETURNING id", record.id, record.owner, record.revision, record.expiresAt, record.status, payload,record.owner,this.limits.maxActivePerOwner,this.limits.maxRecords,payload.length,this.limits.maxBytes)];if(!rows.length)throw new ServiceError('EVENT_CAPACITY','Event consumer storage capacity is exhausted; stop inactive consumers and allow retention cleanup.',503); }
    async get(owner: string, id: string): Promise<EventConsumer | undefined> { const row = [...this.sql.exec('SELECT * FROM event_consumers WHERE id=? AND owner=?', id, owner)][0]; return row ? this.decode(row) : undefined; }
    async list(owner: string): Promise<EventConsumer[]> { return Promise.all([...this.sql.exec("SELECT * FROM event_consumers WHERE owner=? ORDER BY CASE WHEN status='stopped' THEN 1 ELSE 0 END,expires LIMIT 100", owner)].map(row => this.decode(row))); }
    async expired(now: number, limit: number): Promise<EventConsumer[]> { return Promise.all([...this.sql.exec("SELECT * FROM event_consumers WHERE (expires<=? OR owner IN (SELECT owner FROM event_revoked_owners)) AND status NOT IN ('stopped','uncertain','polling') ORDER BY expires LIMIT ?", now, Math.max(1,Math.min(100,limit)))].map(row => this.decode(row))); }
    async prune(before:number):Promise<number>{return [...this.sql.exec("DELETE FROM event_consumers WHERE id IN (SELECT id FROM event_consumers WHERE status='stopped' AND expires<=? LIMIT 100) RETURNING id",before)].length;}
    async transition(record: EventConsumer, expectedRevision: number): Promise<boolean> { if (record.revision !== expectedRevision + 1) throw new ServiceError('INVALID_REVISION', 'Consumer revision must advance exactly once.', 500); const payload = await this.encode(record); const row=[...this.sql.exec('SELECT revision,length(payload) AS bytes FROM event_consumers WHERE id=? AND owner=?',record.id,record.owner)][0]; if(!row || Number(row.revision)!==expectedRevision)return false; const total=Number([...this.sql.exec('SELECT COALESCE(SUM(length(payload)),0) AS bytes FROM event_consumers')][0]?.bytes??0);if(total-Number(row.bytes)+payload.length>this.limits.maxBytes)throw new ServiceError('EVENT_CAPACITY','Encrypted event consumer state exceeds storage capacity.',503);return [...this.sql.exec('UPDATE event_consumers SET revision=?,expires=?,status=?,payload=? WHERE id=? AND owner=? AND revision=? RETURNING id', record.revision, record.expiresAt, record.status, payload, record.id, record.owner, expectedRevision)].length === 1; }
    async join(group: string, consumerId: string, single: boolean): Promise<{ leader: boolean }> {
        const created = [...this.sql.exec("INSERT INTO event_consumer_groups(id,leader,state) VALUES(?,?,'starting') ON CONFLICT(id) DO NOTHING RETURNING id", group, consumerId)].length > 0;
        const current = [...this.sql.exec('SELECT * FROM event_consumer_groups WHERE id=?',group)][0];
        if (!created && current?.state !== 'active') throw new ServiceError('SUBSCRIPTION_BUSY', 'Subscription setup or cleanup is already in progress.', 409);
        if (!created && single && [...this.sql.exec('SELECT consumer_id FROM event_consumer_members WHERE group_id=? LIMIT 1', group)].length) throw new ServiceError('SINGLE_CONSUMER', 'This EventKey already has an active consumer.', 409);
        this.sql.exec('INSERT INTO event_consumer_members(group_id,consumer_id) VALUES(?,?)', group, consumerId); return { leader: created };
    }
    async activate(group: string, consumerId: string): Promise<void> { const rows = [...this.sql.exec("UPDATE event_consumer_groups SET state='active' WHERE id=? AND leader=? AND state='starting' RETURNING id", group, consumerId)]; if (!rows.length) throw new ServiceError('SUBSCRIPTION_STATE', 'Subscription setup lock was lost.', 409); }
    async leave(group: string, consumerId: string): Promise<boolean> { this.sql.exec('DELETE FROM event_consumer_members WHERE group_id=? AND consumer_id=?', group,consumerId); if ([...this.sql.exec('SELECT consumer_id FROM event_consumer_members WHERE group_id=? LIMIT 1',group)].length) return false; return [...this.sql.exec("UPDATE event_consumer_groups SET state='stopping',leader=? WHERE id=? AND state IN ('active','starting') RETURNING id",consumerId,group)].length === 1; }
    async removeGroup(group: string): Promise<void> { this.sql.exec('DELETE FROM event_consumer_groups WHERE id=? AND NOT EXISTS(SELECT 1 FROM event_consumer_members WHERE group_id=?)',group,group); }
}
