import type { JsonObject } from '../../domain/models';
import type { Capability, CommandContext } from '../../ports/capabilities';
import type { WorkflowProgram, WorkflowRunner } from '../../ports/workflows';
import { arr, bounds, csv, invalid, iso, obj, seconds, text } from './helpers';
import { calendarAvailabilityDefinitions } from './availability-definitions';
const path = '/open-apis/calendar/v4/freebusy';
async function attendees(args: JsonObject, context?: CommandContext): Promise<JsonObject> {
    const users: string[] = [], chats: string[] = [];
    for (const id of csv(args['attendee-ids'])) { if (id.startsWith('ou_')) users.push(id); else if (id.startsWith('oc_')) chats.push(id); else invalid('Attendees must be user or chat IDs.'); }
    if (context?.selection.identity === 'user') { const me = await context.lark.request({ method: 'GET', path: '/open-apis/authen/v1/user_info' }); if (me.open_id) users.push(String(me.open_id)); }
    return { ...(users.length ? { attendee_user_ids: [...new Set(users)] } : {}), ...(chats.length ? { attendee_chat_ids: [...new Set(chats)] } : {}) };
}
function pair(value: string, endDay = false): [number, number] { const parts = value.split('~'); if (parts.length !== 2) invalid('Time slots require start~end.'); const start = seconds(parts[0]!), end = seconds(parts[1]!, endDay); if (end <= start) invalid('Slot end must follow start.'); return [start, end]; }
function duration(value: string): number { if (!value || value === '0') return 0; let total = 0, consumed = ''; for (const m of value.matchAll(/(\d+(?:\.\d+)?)(h|ms|m|s)/g)) { consumed += m[0]; total += Number(m[1]) * ({ h: 3600, m: 60, s: 1, ms: .001 }[m[2]!] ?? 0); } if (consumed !== value) invalid('min-duration must be a nonnegative duration such as 30m.'); return total; }
type Interval = [number, number];
function merge(values: Interval[]): Interval[] { const result: Interval[] = []; for (const [start, end] of values.sort((a, b) => a[0] - b[0])) { const previous = result.at(-1); if (previous && previous[1] >= start) previous[1] = Math.max(previous[1], end); else result.push([start, end]); } return result; }
function free(values: Interval[], start: number, end: number, minimum: number): Interval[] { const result: Interval[] = []; let cursor = start; for (const [a, b] of merge(values)) { if (a > cursor) result.push([cursor, Math.min(a, end)]); cursor = Math.max(cursor, b); if (cursor >= end) break; } if (cursor < end) result.push([cursor, end]); return result.filter(([a, b]) => b > a && b - a >= minimum); }
function formatted(values: Interval[], withDuration = false): JsonObject[] { return values.map(([a, b]) => { const d = b - a; return { start_time: iso(a), end_time: iso(b), ...(withDuration ? { duration: d >= 3600 ? `${Math.floor(d / 3600)}h${Math.floor(d % 3600 / 60)}m${d % 60}s` : d >= 60 ? `${Math.floor(d / 60)}m${d % 60}s` : `${d}s` } : {}) }; }); }
async function suggestion(args: JsonObject, context?: CommandContext): Promise<JsonObject> { const [start, end] = bounds(args, 'suggestion'), minutes = Number(args['duration-minutes'] ?? 0); if (!Number.isInteger(minutes) || minutes < 0 || minutes > 1440) invalid('duration-minutes must be 0 to 1440.'); return { search_start_time: iso(start), search_end_time: iso(end), ...await attendees(args, context), ...(minutes ? { duration_minutes: minutes } : {}), ...(text(args, 'timezone') ? { timezone: text(args, 'timezone') } : {}), ...(text(args, 'event-rrule') ? { event_rrule: text(args, 'event-rrule') } : {}), ...(csv(args.exclude).length ? { excluded_event_times: csv(args.exclude).map(value => { const [a, b] = pair(value, true); return { event_start_time: iso(a), event_end_time: iso(b) }; }) } : {}) }; }
function roomBody(args: JsonObject): JsonObject {
    const body: JsonObject = {}; for (const key of ['city', 'building', 'floor', 'room-name', 'timezone', 'event-rrule']) if (text(args, key)) body[key.replaceAll('-', '_')] = key === 'timezone' || key === 'event-rrule' ? text(args, key) : csv(args[key]).join(',');
    for (const key of ['min-capacity', 'max-capacity']) { const value = Number(args[key] ?? 0); if (!Number.isInteger(value) || value < 0) invalid('Room capacities must be nonnegative integers.'); if (value) body[key.replace('-', '_')] = value; }
    if (body.min_capacity && body.max_capacity && Number(body.min_capacity) > Number(body.max_capacity)) invalid('min-capacity exceeds max-capacity.'); return body;
}
export function calendarAvailabilityCapabilities(workflows: WorkflowRunner): Capability[] { return calendarAvailabilityDefinitions.map(definition => ({ definition, preview: async args => { const action = definition.id.slice(10); return { requests: [{ method: 'POST', path: `${path}/${action === 'freebusy' ? 'batch' : action.replace('-', '_')}`, body: action === 'suggestion' ? await suggestion(args) : action === 'room-find' ? roomBody(args) : { time_min: iso(bounds(args)[0]), time_max: iso(bounds(args)[1]), user_ids: csv(args['user-id']), need_rsvp_status: true } }] }; }, execute: async (args, context) => {
    const action = definition.id.slice(10);
    if (action === 'suggestion') return context.lark.request({ method: 'POST', path: `${path}/suggestion`, body: await suggestion(args, context) });
    if (action === 'room-find') { const slots = Array.isArray(args.slot) ? args.slot.map(String) : [text(args, 'slot')]; if (!slots.length || slots.some(s => !s)) invalid('At least one slot is required.'); slots.forEach(s => pair(s)); roomBody(args); await attendees(args); return workflows.start('calendar-room-find', { args, phase: context.selection.identity === 'user' ? 'identity' : 'rooms', index: 0, results: [] }, context.selection, context.grant); }
    const [start, end] = bounds(args); if (end <= start) invalid('End must follow start.'); const type = text(args, 'type') || 'busy'; if (!['busy', 'raw_busy', 'free', 'common_free'].includes(type)) invalid('Invalid freebusy type.'); const minimum = duration(text(args, 'min-duration')); let ids = [...new Set(csv(args['user-id']))]; if (!ids.length) { if (context.selection.identity === 'bot') invalid('Bot freebusy requires user-id.'); const me = await context.lark.request({ method: 'GET', path: '/open-apis/authen/v1/user_info' }); ids = [String(me.open_id ?? '')]; } if (ids.some(id => !id.startsWith('ou_'))) invalid('user-id must contain open IDs.');
    const data = await context.lark.request({ method: 'POST', path: `${path}/batch`, body: { time_min: iso(start), time_max: iso(end), user_ids: ids, need_rsvp_status: true } });
    const all: Interval[] = []; const users = ids.map(id => { const rows = arr(obj(arr(data.freebusy_lists).find(item => obj(item).user_id === id)).freebusy_items).map(obj); const intervals = rows.map(row => [Date.parse(String(row.start_time)) / 1000, Date.parse(String(row.end_time)) / 1000] as Interval).filter(([a, b]) => Number.isFinite(a) && b > a); all.push(...intervals); return { user_id: id, [type === 'raw_busy' ? 'raw_busy' : type === 'free' ? 'free' : 'busy']: type === 'raw_busy' ? rows.sort((a, b) => String(a.start_time).localeCompare(String(b.start_time))) : formatted(type === 'free' ? free(intervals, start, end, minimum) : merge(intervals), type === 'free') }; });
    return type === 'common_free' ? { common_free: formatted(free(all, start, end, minimum), true) } : { users };
} })); }
export function calendarAvailabilityPrograms(): WorkflowProgram[] { return [{ id: 'calendar-room-find', version: 1, domain: 'calendar', risk: 'read', identities: ['user', 'bot'], step: async (state, context) => {
    const args = obj(state.args); if (state.phase === 'identity') return { done: false, state: { ...state, attendees: await attendees(args, context), phase: 'rooms' } };
    const slots = Array.isArray(args.slot) ? args.slot.map(String) : [text(args, 'slot')], index = Number(state.index ?? 0), results = arr(state.results).map(obj); if (index >= slots.length) return { done: true, output: { time_slots: results.sort((a, b) => String(a.start).localeCompare(String(b.start))) } };
    const [start, end] = pair(slots[index]!); const data = await context.lark.request({ method: 'POST', path: `${path}/room_find`, body: { ...roomBody(args), ...(state.attendees ? obj(state.attendees) : await attendees(args)), event_start_time: iso(start), event_end_time: iso(end) } }); const rooms = arr(data.available_rooms); results.push({ start: iso(start), end: iso(end), meeting_rooms: rooms, ...(!rooms.length ? { hint: 'no meeting room matches the current filters for this slot' } : {}) }); return { done: false, state: { ...state, index: index + 1, results } };
} }]; }
