import { calendarCreateDefinition } from './create-definition';
export { calendarCreateDefinition } from './create-definition';
import type { ArtifactStore } from '../../ports/artifacts';
import { hasArtifactImage, resolveCalendarDescription, validateDescription } from './description';
import { ServiceError, safeError } from '../../domain/errors';
import type { CommandDefinition, JsonObject } from '../../domain/models';
import type { Capability } from '../../ports/capabilities';
import type { WorkflowProgram, WorkflowRunner } from '../../ports/workflows';
import { base, calendar, csv, eventOutput, invalid, obj, seconds, text } from './helpers';
export function parseAttendees(value: unknown): JsonObject[] { return [...new Set(csv(value))].map(id => { if (id.startsWith('ou_')) return { type: 'user', user_id: id }; if (id.startsWith('oc_')) return { type: 'chat', chat_id: id }; if (id.startsWith('omm_')) return { type: 'resource', room_id: id }; return invalid('Attendee IDs must start with ou_, oc_, or omm_.'); }); }
export function createBody(args: JsonObject): JsonObject {
    validateDescription(String(args.description ?? ''));
    const start = seconds(text(args, 'start')), end = seconds(text(args, 'end'), true); if (end <= start) invalid('Event end must follow start.'); parseAttendees(args['attendee-ids']); const owner = text(args, 'meeting-owner-id'); if (owner && !/^ou_.+/.test(owner)) invalid('meeting-owner-id must be an open ID.');
    return { summary: args.summary ?? '', start_time: { timestamp: String(start) }, end_time: { timestamp: String(end) }, attendee_ability: 'can_modify_event', free_busy_status: 'busy', vchat: { vc_type: 'vc', ...(owner ? { meeting_settings: { owner_id: owner } } : {}) }, reminders: [{ minutes: 5 }], ...(args.description ? { description_rich: args.description } : {}), ...(args.rrule ? { recurrence: args.rrule } : {}) };
}

export function calendarCreateCapability(workflows: WorkflowRunner): Capability { return { definition: calendarCreateDefinition, preview: async args => ({ requests: [{ method: 'POST', path: `${base}/${encodeURIComponent(calendar(args))}/events`, body: createBody(args) }] }), execute: async (args, context) => { createBody(args); if (text(args, 'meeting-owner-id') && context.selection.identity !== 'bot') invalid('meeting-owner-id requires bot identity.'); return workflows.start('calendar-create', { args, phase: 'create' }, context.selection, context.grant); } }; }
export function calendarCreateProgram(artifacts?: ArtifactStore): WorkflowProgram { return { id: 'calendar-create', version: 1, domain: 'calendar', risk: 'write', identities: ['user', 'bot'], step: async (state, context) => {
    const args = obj(state.args), path = `${base}/${encodeURIComponent(calendar(args))}/events`, event = obj(state.event);
    if (state.phase === 'create' && hasArtifactImage(String(args.description ?? ''))) return { done: false, state: { ...state, args: { ...args, description: await resolveCalendarDescription(String(args.description), calendar(args), context, artifacts) } } };
    if (state.phase === 'create') { const data = await context.lark.request({ method: 'POST', path, body: createBody(args) }); if (!obj(data.event).event_id) throw new ServiceError('INVALID_RESPONSE', 'Created event response omitted event_id.', 502); return { done: false, state: { ...state, event: data.event, phase: text(args, 'attendee-ids') ? 'identity' : 'done' } }; }
    if (state.phase === 'identity') { let self = ''; try { const data = await context.lark.request({ method: 'GET', path: context.selection.identity === 'user' ? '/open-apis/authen/v1/user_info' : '/open-apis/bot/v3/info/' }); self = String(data.open_id ?? obj(data.bot).open_id ?? ''); } catch (error) { if (context.selection.identity === 'user') throw error; } return { done: false, state: { ...state, phase: 'attendees', attendees: parseAttendees([...csv(args['attendee-ids']), ...(self ? [self] : [])]) } }; }
    if (state.phase === 'attendees') { try { await context.lark.request({ method: 'POST', path: `${path}/${encodeURIComponent(String(event.event_id))}/attendees`, query: { user_id_type: 'open_id' }, body: { attendees: state.attendees, need_notification: true } }); return { done: false, state: { ...state, phase: 'done' } }; } catch (error) { if (!(error instanceof ServiceError) || !['UPSTREAM_ERROR', 'LARK_API_ERROR'].includes(error.code)) throw error; return { done: false, state: { ...state, phase: 'rollback', failure: safeError(error) } }; } }
    if (state.phase === 'rollback') { const failure = obj(state.failure); try { await context.lark.request({ method: 'DELETE', path: `${path}/${encodeURIComponent(String(event.event_id))}`, query: { need_notification: false } }); } catch { throw new ServiceError(String(failure.code), `${failure.message}; rollback failed; event ${event.event_id} requires manual cleanup.`, 502, { event_id: event.event_id }); } throw new ServiceError(String(failure.code), `${failure.message}; event rolled back successfully.`, 502); }
    const output = eventOutput(event); return { done: true, output: { event_id: event.event_id, summary: event.summary ?? '', start: obj(output.start_time).datetime ?? obj(output.start_time).date ?? '', end: obj(output.end_time).datetime ?? obj(output.end_time).date ?? '', ...(event.recurrence ? { recurrence: event.recurrence } : {}) } };
} }; }
