import type { ArtifactStore } from '../../ports/artifacts';
import { hasArtifactImage, resolveCalendarDescription, validateDescription } from './description';
import { ServiceError, safeError } from '../../domain/errors';
import type { JsonObject } from '../../domain/models';
import type { Capability } from '../../ports/capabilities';
import type { ApiRequest } from '../../ports/lark';
import type { WorkflowProgram, WorkflowRunner } from '../../ports/workflows';
import { arr, base, calendar, csv, eventId, eventOutput, eventPath, invalid, iso, obj, seconds, text } from './helpers';
import { parseAttendees } from './create';
import { eventSeconds, masterId, originalTime, pivotMidnight, recurringEnd, recurringScope, truncateRule } from './recurring';
import { calendarMutationDefinitions } from './mutation-definitions';
export function updateBody(args: JsonObject): JsonObject { validateDescription(String(args.description ?? '')); const body: JsonObject = {}; for (const [key, field] of [['summary', 'summary'], ['description', 'description_rich']] as const) if (key in args) body[field] = args[key]; if (text(args, 'rrule')) body.recurrence = text(args, 'rrule'); if (('start' in args) !== ('end' in args)) invalid('start and end must be provided together.'); if ('start' in args) { const start = seconds(text(args, 'start')), end = seconds(text(args, 'end'), true); if (end <= start) invalid('End must follow start.'); body.start_time = { timestamp: String(start) }; body.end_time = { timestamp: String(end) }; } if (Object.keys(body).length) body.need_notification = args.notify !== false; parseAttendees(args['add-attendee-ids']); parseAttendees(args['remove-attendee-ids']); return body; }
export function calendarMutationCapabilities(workflows: WorkflowRunner): Capability[] { return calendarMutationDefinitions.map(definition => ({ definition, preview: async args => { eventId(args, true); if (definition.id.endsWith('update')) updateBody(args); return { requests: [{ method: 'GET', path: eventPath(args, true) }], description: 'Classify the event before selecting recurring scope, room checks, exception handling and writes.' }; }, execute: async (args, context) => { const action = definition.id.endsWith('delete') ? 'delete' : 'update'; eventId(args, true); if (action === 'update') { const body = updateBody(args); if (!Object.keys(body).length && !csv(args['add-attendee-ids']).length && !csv(args['remove-attendee-ids']).length) invalid('At least one changed event field or attendee is required.'); } return workflows.start('calendar-mutation', { action, args, phase: 'read' }, context.selection, context.grant); } })); }
function operations(args: JsonObject, id: string, omitTime = false, exception = false): ApiRequest[] { const path = eventPath({ ...args, 'event-id': id }), body = updateBody(args), requests: ApiRequest[] = []; if (omitTime) { delete body.start_time; delete body.end_time; delete body.need_notification; if (Object.keys(body).length) body.need_notification = args.notify !== false; } if (exception && Object.keys(body).length) body.need_notification = false; if (Object.keys(body).length) requests.push({ method: 'PATCH', path, query: { user_id_type: 'open_id' }, body }); for (const [key, suffix, field] of [['remove-attendee-ids', '/batch_delete', 'delete_ids'], ['add-attendee-ids', '', 'attendees']]) { const list = parseAttendees(args[key!]); if (list.length) requests.push({ method: 'POST', path: `${path}/attendees${suffix}`, query: { user_id_type: 'open_id' }, body: { [field!]: list, need_notification: exception ? false : args.notify !== false } }); } return requests; }
function deletion(args: JsonObject, id: string, exception = false): ApiRequest { return { method: 'DELETE', path: eventPath({ ...args, 'event-id': id }), query: { need_notification: exception ? false : args.notify !== false, ...(exception ? { delete_exception: true } : {}) } }; }
export function calendarMutationProgram(artifacts?: ArtifactStore): WorkflowProgram { return { id: 'calendar-mutation', version: 1, domain: 'calendar', risk: 'write', identities: ['user', 'bot'], step: async (state, context) => {
    const args = obj(state.args), action = String(state.action), id = eventId(args, true), current = obj(state.current), master = obj(state.master), scope = String(state.scope ?? ''), phase = String(state.phase), advance = (extra: JsonObject) => ({ done: false as const, state: { ...state, ...extra } });
    if (phase === 'read' && hasArtifactImage(String(args.description ?? ''))) return advance({ args: { ...args, description: await resolveCalendarDescription(String(args.description), calendar(args), context, artifacts) } });
    if (phase === 'read') { const data = await context.lark.request({ method: 'GET', path: eventPath(args, true), ...(action === 'update' ? { query: { user_id_type: 'open_id', need_attendee: true, max_attendee_num: 20 } } : {}) }); if (!data.event) throw new ServiceError('INVALID_RESPONSE', 'Calendar response omitted event.', 502); const event = obj(data.event), selected = recurringScope(event, id, text(args, 'apply-to')); return advance({ current: event, scope: selected, master: event, phase: selected !== 'single' && id !== masterId(id) ? 'master' : 'prepare' }); }
    if (phase === 'master') { const data = await context.lark.request({ method: 'GET', path: eventPath({ ...args, 'event-id': masterId(id) }), ...(action === 'update' ? { query: { user_id_type: 'open_id', need_attendee: true, max_attendee_num: 20 } } : {}) }); if (!obj(data.event).recurrence) invalid('The recurring master has no recurrence rule.'); return advance({ master: data.event, phase: 'prepare' }); }
    if (phase === 'prepare') {
        const target = scope === 'single' ? current : master, mid = scope === 'single' ? id : String(master.event_id || masterId(id)), body = action === 'update' ? updateBody(args) : {}, changed = 'start' in args && (obj(master.start_time).date && obj(master.end_time).date ? text(args, 'start') !== obj(master.start_time).date || text(args, 'end') !== obj(master.end_time).date : Number(obj(body.start_time).timestamp) !== eventSeconds(master, 'start_time') || Number(obj(body.end_time).timestamp) !== eventSeconds(master, 'end_time'));
        const timezone = String(obj(master.start_time).timezone || obj(master.end_time).timezone || 'UTC'), pivot = scope === 'this-and-following' ? pivotMidnight(originalTime(id), timezone) : 0, start = pivot || eventSeconds(master, 'start_time');
        const next: JsonObject = { mid, timeChanged: changed, pivot, scanStart: start, scanEnd: recurringEnd(String(master.recurrence ?? ''), start), exceptions: [], failures: [], phase: scope === 'single' ? 'queue' : 'scan' };
        if (action === 'update' && args['skip-room-check'] !== true && scope !== 'this-and-following') { const removed = csv(args['remove-attendee-ids']), rooms = [...new Set([...csv(args['add-attendee-ids']).filter(v => v.startsWith('omm_')), ...(('start' in args || 'rrule' in args) ? arr(target.attendees).map(obj).filter(a => a.type === 'resource' && a.rsvp_status !== 'removed').map(a => String(a.room_id ?? '')) : [])])].filter(v => v && !removed.includes(v)); const from = Number(obj(body.start_time).timestamp) || eventSeconds(target, 'start_time'), to = Number(obj(body.end_time).timestamp) || eventSeconds(target, 'end_time'); if (rooms.length && from && to) { next.afterRoom = next.phase; next.phase = 'room'; next.roomBody = { calendar_id: calendar(args), event_id: mid, start_time: iso(from), end_time: iso(to), room_ids: rooms, ...(obj(target.start_time).timezone ? { start_timezone: obj(target.start_time).timezone } : {}), ...(text(args, 'rrule') || target.recurrence ? { event_rrule: text(args, 'rrule') || target.recurrence } : {}) }; } }
        return advance(next);
    }
    if (phase === 'room') { const data = await context.lark.request({ method: 'POST', path: '/open-apis/calendar/v4/freebusy/room_availability_check', body: state.roomBody }); const blocked = arr(data.room_availabilitys).map(obj).filter(room => room.status !== 'available'); if (blocked.length) throw new ServiceError('ROOM_UNAVAILABLE', 'Requested meeting rooms are unavailable or require approval.', 409, { rooms: blocked }); return advance({ phase: state.afterRoom }); }
    if (phase === 'scan') {
        const start = Number(state.scanStart), end = Number(state.scanEnd); if (start >= end) return advance({ phase: 'queue' }); const chunk = Math.min(end, start + 365 * 86400), token = String(state.pageToken ?? ''); const data = await context.lark.request({ method: 'GET', path: `${eventPath({ ...args, 'event-id': String(state.mid) })}/instances`, query: { start_time: String(start), end_time: String(chunk), page_size: 500, ...(token ? { page_token: token } : {}) } }); const existing = arr(state.exceptions).map(obj), seen = new Set(existing.map(e => e.event_id));
        for (const event of arr(data.items).map(obj)) { const eid = String(event.event_id ?? ''); if (event.is_exception !== true || !eid || seen.has(eid) || action === 'update' && scope === 'all' && !state.timeChanged && event.status === 'cancelled' || scope === 'this-and-following' && (eventSeconds(event, 'start_time') || originalTime(eid)) < originalTime(id)) continue; seen.add(eid); existing.push({ event_id: eid, start: eventSeconds(event, 'start_time') || originalTime(eid) }); } if (existing.length > 5000) invalid('Recurring series exceeds 5000 exceptions; narrow the operation.'); const next = data.has_more === true ? String(data.page_token ?? '') : ''; if (next && next === token) throw new ServiceError('INVALID_RESPONSE', 'Recurring instance cursor repeated.', 502); return advance({ exceptions: existing, pageToken: next, scanStart: next ? start : chunk + 1 });
    }
    if (phase === 'queue') {
        const now = Date.now() / 1000, exceptions = arr(state.exceptions).map(obj).sort((a, b) => { const x = Number(a.start), y = Number(b.start); return x >= now && y < now ? -1 : x < now && y >= now ? 1 : x >= now ? x - y : y - x; }), exceptionIndex = Number(state.exceptionIndex ?? 0);
        const queue: JsonObject[] = [], event = exceptions[exceptionIndex];
        if (event) { const eid = String(event.event_id); for (const request of action === 'delete' || state.timeChanged || scope === 'this-and-following' ? [deletion(args, eid, true)] : operations(args, eid, true, true)) queue.push({ request, exceptionId: eid }); }
        else if (scope === 'this-and-following') queue.push({ request: { method: 'PATCH', path: eventPath({ ...args, 'event-id': String(state.mid) }), query: { user_id_type: 'open_id' }, body: { recurrence: truncateRule(String(master.recurrence), Number(state.pivot)), need_notification: args.notify !== false } } });
        else for (const request of action === 'delete' ? [deletion(args, String(state.mid))] : operations(args, String(state.mid), scope === 'all' && !state.timeChanged)) queue.push({ request });
        return advance({ queue, index: 0, exceptionIndex, exceptions, queueException: Boolean(event), phase: 'write' });
    }
    if (phase === 'write') {
        if (Number(state.nextAllowed ?? 0) > Date.now()) return advance({});
        const queue = arr(state.queue).map(obj), index = Number(state.index); if (index >= queue.length) return advance(state.queueException ? { phase: 'queue', exceptionIndex: Number(state.exceptionIndex ?? 0) + 1, queue: [] } : { phase: scope === 'this-and-following' && action === 'update' ? 'following-create' : 'done', queue: [] }); const item = queue[index]!, request = item.request as unknown as ApiRequest;
        try { const data = await context.lark.request(request); return advance({ index: index + 1, retry: 0, nextAllowed: 0, ...(data.event && !item.exceptionId ? { updated: data.event } : {}) }); } catch (error) { const code = error instanceof ServiceError ? Number(error.details?.upstreamCode ?? error.details?.code) : 0; if (item.exceptionId && [99991400, 190004, 190005, 190010].includes(code) && Number(state.retry ?? 0) < 5) { const retry = Number(state.retry ?? 0), delay = Math.min(10000, 500 * 2 ** retry); return advance({ retry: retry + 1, nextAllowed: Date.now() + delay + Math.floor(Math.random() * delay / 5) }); } if (request.method === 'DELETE' && code === 193003) return advance({ index: index + 1, retry: 0, nextAllowed: 0 }); if (!item.exceptionId || !(error instanceof ServiceError) || !['UPSTREAM_ERROR', 'LARK_API_ERROR'].includes(error.code)) throw error; return advance({ index: index + 1, retry: 0, nextAllowed: 0, failures: [...arr(state.failures), { event_id: item.exceptionId, ...safeError(error) }] }); }
    }
    if (phase === 'following-create') {
        const body: JsonObject = { summary: master.summary ?? '', attendee_ability: master.attendee_ability || 'can_modify_event', free_busy_status: master.free_busy_status || 'busy', reminders: arr(master.reminders).length ? master.reminders : [{ minutes: 5 }], color: master.color ?? 0 }; for (const key of ['vchat', 'location', 'visibility', 'attachments', 'event_check_in']) if (master[key] !== undefined) body[key] = master[key]; body.description_rich = master.description_rich || master.description || ''; const start = 'start' in args ? seconds(text(args, 'start')) : eventSeconds(current, 'start_time') || originalTime(id), end = 'end' in args ? seconds(text(args, 'end'), true) : eventSeconds(current, 'end_time'); if (end <= start) invalid('Cannot resolve the following series duration.'); body.start_time = { timestamp: String(start), ...(obj(master.start_time).timezone ? { timezone: obj(master.start_time).timezone } : {}) }; body.end_time = { timestamp: String(end), ...(obj(master.end_time).timezone ? { timezone: obj(master.end_time).timezone } : {}) }; const rule = 'rrule' in args ? text(args, 'rrule') : String(master.recurrence ?? '').split(';').filter(part => !/^COUNT=/i.test(part)).join(';'); if (rule) body.recurrence = rule; if ('summary' in args) body.summary = args.summary; if ('description' in args) body.description_rich = args.description;
        const data = await context.lark.request({ method: 'POST', path: `${base}/${encodeURIComponent(calendar(args))}/events`, body }); if (!obj(data.event).event_id) throw new ServiceError('INVALID_RESPONSE', 'Master truncated but following series response omitted event_id.', 502); return advance({ following: data.event, phase: 'inherit', pageToken: '', inherited: [] });
    }
    if (phase === 'inherit') { const token = String(state.pageToken ?? ''); const data = await context.lark.request({ method: 'GET', path: `${eventPath({ ...args, 'event-id': String(state.mid) })}/attendees`, query: { page_size: 100, user_id_type: 'open_id', ...(token ? { page_token: token } : {}) } }); const inherited = [...arr(state.inherited), ...arr(data.items).map(obj).filter(a => ['user', 'chat', 'resource', 'third_party'].includes(String(a.type)) && Boolean(a.user_id || a.chat_id || a.room_id || a.third_party_email)).map(a => Object.fromEntries(['type', 'user_id', 'chat_id', 'room_id', 'third_party_email', 'resource_customization'].filter(key => a[key] !== undefined).map(key => [key, a[key]])))]; const next = data.has_more === true ? String(data.page_token ?? '') : ''; if (next && next === token) throw new ServiceError('INVALID_RESPONSE', 'Attendee cursor repeated.', 502); return advance({ inherited, pageToken: next, phase: next ? 'inherit' : 'following-attendees' }); }
    if (phase === 'following-attendees') { const removed = csv(args['remove-attendee-ids']), key = (a: JsonObject) => String(a.user_id || a.chat_id || a.room_id || a.third_party_email), unique = new Map(arr(state.inherited).map(obj).filter(a => !removed.includes(key(a))).map(a => [key(a), a])); for (const attendee of parseAttendees(args['add-attendee-ids'])) if (!unique.has(key(attendee))) unique.set(key(attendee), attendee); if (unique.size) await context.lark.request({ method: 'POST', path: `${eventPath({ ...args, 'event-id': String(obj(state.following).event_id) })}/attendees`, query: { user_id_type: 'open_id' }, body: { attendees: [...unique.values()], need_notification: args.notify !== false } }); return advance({ phase: 'done' }); }
    const failures = arr(state.failures), count = arr(state.exceptions).length, event = obj(state.following || state.updated), detail: JsonObject = { event_id: event.event_id || state.mid, attendees_added_count: parseAttendees(args['add-attendee-ids']).length, attendees_removed_count: parseAttendees(args['remove-attendee-ids']).length }; for (const key of ['summary']) if (event[key]) detail[key] = event[key]; if (event.description_rich || event.description) detail.description = event.description_rich || event.description; for (const [field, name] of [['start_time', 'start'], ['end_time', 'end']]) { const value = obj(event[field!]); if (value.timestamp) detail[name!] = iso(Number(value.timestamp)); else if (value.date) detail[name!] = value.date; } if (state.following && event.recurrence) detail.rrule = event.recurrence; const output: JsonObject = { calendar_id: calendar(args), apply_to: scope, ...(count ? { exceptions: { total: count, [action === 'delete' || state.timeChanged || scope === 'this-and-following' ? 'deleted' : 'updated']: count - new Set(failures.map(f => obj(f).event_id)).size, failed: new Set(failures.map(f => obj(f).event_id)).size, ...(failures.length ? { failures } : {}) } } : {}) };
    if (scope === 'this-and-following') { output.truncated_event = { master_event_id: state.mid, rrule_truncated: truncateRule(String(master.recurrence), Number(state.pivot)) }; if (action === 'update') output.follow_event = detail; } else output[action === 'delete' ? 'deleted_event' : 'updated_event'] = { ...(action === 'update' ? detail : {}), event_id: state.mid, action: action === 'delete' ? 'deleted' : 'patched', ...(action === 'update' ? { attendees_added_count: parseAttendees(args['add-attendee-ids']).length, attendees_removed_count: parseAttendees(args['remove-attendee-ids']).length } : {}) }; return { done: true, output };
} }; }
