import { mkdir, readFile, writeFile } from 'node:fs/promises';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { commandDefinitions } from '../../src/capabilities/definitions.ts';

const schemas = commandDefinitions.map((item) => item.inputSchema);
const unique = [...new Map(schemas.map((schema) => [JSON.stringify(schema), schema])).entries()];
const ajv = new Ajv({ strict: false, allErrors: true, coerceTypes: false, code: { source: true, esm: true } });
const exports: Record<string, string> = {};
unique.forEach(([, schema], index) => {
    const name = `compiled${index}`;
    ajv.addSchema(schema, name);
    exports[name] = name;
});
const code = '// @ts-nocheck\n// Generated by scripts/validation/generate.ts. Do not edit.\n' +
    standaloneCode(ajv, exports) + '\nexport const compiledSchemas = new Map([\n' +
    unique.map(([schema], index) => `    [${JSON.stringify(schema)}, compiled${index}],`).join('\n') + '\n]);\n';
const target = 'src/infrastructure/validation/generated/validators.ts';
if (process.argv.includes('--check')) {
    if (await readFile(target, 'utf8') !== code) throw new Error('Generated validators are stale. Run pnpm generate:validators.');
} else {
    await mkdir('src/infrastructure/validation/generated', { recursive: true });
    await writeFile(target, code);
}
console.log(`Verified ${unique.length} precompiled command schemas.`);
